### PR TITLE
use contextmanager to open/close files

### PR DESCRIPTION
**Pull request by kain88-de**
This helps cleaning up files access and ensures that they are closed
again. This will stop the leaks happening.

### CODE REVIEW

**Comment by abradle** [comment]
thanks! nice

**Comment by kain88-de** [comment]
Hi do you mind making a release? I'm tracking warnings in MDAnalysis testsuite and mmtf currently has a lot of resource warnings because of the open file leaks.

Also happy new year!

**Comment by abradle** [comment]
Should be released now - 1.0.10. Thanks for the fix! Let me know if any
problems.

Best wishes,

Anthony

**Comment by kain88-de** [comment]
Thanks. I also updated the conda-forge  package.

**Comment by abradle** [comment]
I wasn't even aware you'd made one! That's awesome. I love open-source
projects when that happens!

**Pull request merged**
