### PR TITLE
Downloading reduced files

### PR DESCRIPTION
**Pull request by marshuang80**
Added parameter "reduced" for function "get_raw_data_from_url" to allow users to download reduced mmtf files.

### CODE REVIEW

**Comment by abradle** [comment]
References this issue: 
https://github.com/rcsb/mmtf-python/issues/35

Build was failing due to msgpack dependency. Will try and look at the code this week.

Thanks for the PR!

**Comment by abradle** [comment]
One minor change if you could - make the get_url function have reduced as keyword arg.

def get_url(pdb_id,reduced): ->> def get_url(pdb_id,reduced=False):
Just so it doesn't break the API for others.

@arose any issues you see?

Best wishes,

Anthony

**Comment by marshuang80** [comment]
Hi Anthony, 

I just added the minor change you've instructed, let me know if there's anything else I can modify.

Best regards, 
Mars Huang

**Review by abradle — APPROVED** [review]
Looks good to me!

**Comment by abradle** [comment]
Excellent - I see no harm in this at all! 

I've released through pip too. version 1.0.11.

**Pull request merged**
