### PR TITLE
changing ascii to utf8

### PR DESCRIPTION
**Pull request by yuy079**

### CODE REVIEW

**Comment by abradle** [comment]
Thanks Yue.

For everyone else here is the reason for this fix.

"""My name is Yue and I'm currently working at SDSC. I'm starting to work on the mmtf-Pyspark project but while reading the data, my program failed. After checking the data, I realized the problem was because one character in the data was not an ASCII character but the mmtf-python is using decode('ascii').
  So I changed all the 'ascii' to 'utf8' in the file mmtf_reader.py. After the change, I tested again on my code and now it works fine and I made a pull request about it!"""

**Comment by abradle** [comment]
I think this looks good - and works. @arose @josemduarte does anyone have any objections - but this looks sensible to me? Thanks @yuy079

**Comment by josemduarte** [comment]
Looks good to me

**Comment by arose** [comment]
lgtm

**Pull request merged**
